const fs = require("fs");
const path = require("path");
const { collectTrends, containsBlockedContent } = require("./zedge");
const { generatePromptsWithGemini, isDuplicate, loadUsedPrompts, cleanupOldPrompts } = require("./gemini-prompts");
const { StableAudioAPI, createAudioFilename } = require("./stable-audio");
const {
  getApiKey,
  markKeyExhausted,
  markAccountExhausted,
  getWorkingApiKey,
} = require("./account-manager");

const OUTPUT_DIR = path.join(__dirname, "output");
const DAILY_QUOTA = 50;
const MAX_DURATION = 30;
const MIN_DURATION = 5;

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";

function ensureOutputDir() {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }
}

function getTodayString() {
  return new Date().toISOString().split("T")[0];
}

function getProgressFile() {
  const today = getTodayString();
  return path.join(OUTPUT_DIR, `progress_${today}.json`);
}

function loadProgress() {
  const file = getProgressFile();
  try {
    if (fs.existsSync(file)) return JSON.parse(fs.readFileSync(file, "utf-8"));
  } catch {}
  return { date: getTodayString(), completed: 0, failed: 0, tracks: [], errors: [] };
}

function saveProgress(progress) {
  fs.writeFileSync(getProgressFile(), JSON.stringify(progress, null, 2), "utf-8");
}

function calculateDuration(prompt) {
  const words = prompt.split(/\s+/).length;
  let duration;
  if (words < 10) duration = 8;
  else if (words < 20) duration = 12;
  else if (words < 30) duration = 18;
  else if (words < 50) duration = 25;
  else duration = MAX_DURATION;

  const jitter = Math.floor(Math.random() * 5) - 2;
  duration = Math.min(Math.max(duration + jitter, MIN_DURATION), MAX_DURATION);
  return duration;
}

async function generateTrack(apiClient, prompt, trackNumber) {
  if (containsBlockedContent(prompt.prompt)) {
    console.warn(`  [${trackNumber}] SKIPPED: Contains blocked/copyrighted content`);
    return { success: false, error: "blocked_content", prompt: prompt.prompt };
  }

  const duration = calculateDuration(prompt.prompt);
  const filename = createAudioFilename(prompt.prompt, trackNumber);
  const outputPath = path.join(OUTPUT_DIR, filename);

  console.log(`  [${trackNumber}/${DAILY_QUOTA}] Generating: "${prompt.prompt.substring(0, 60)}..." (${duration}s)`);

  try {
    await apiClient.generate({
      prompt: prompt.prompt,
      duration,
      outputPath,
    });

    console.log(`  [${trackNumber}] Saved: ${filename}`);
    return { success: true, filename, duration, prompt: prompt.prompt, isOriginal: true };
  } catch (err) {
    if (err.message === "QUOTA_EXCEEDED") {
      throw err;
    }
    console.error(`  [${trackNumber}] Failed: ${err.message}`);
    return { success: false, error: err.message, prompt: prompt.prompt };
  }
}

async function rotateApiKey(currentKey) {
  console.log("\n  [Rotation] API key exhausted. Switching...");
  markKeyExhausted(currentKey);

  const next = getWorkingApiKey();
  if (next) {
    console.log(`  [Rotation] Switched to key: ${next.apiKey.key.substring(0, 15)}...`);
    return next.apiKey.key;
  }

  console.log("  [Rotation] No more keys. Registering new account...");
  try {
    const newAcc = await (require("./account-manager").registerNewAccount)();
    return newAcc.apiKey;
  } catch (err) {
    console.error(`  [Rotation] Registration failed: ${err.message}`);
    return null;
  }
}

async function getPromptsFromGemini(count, trends) {
  if (!GEMINI_API_KEY) {
    console.log("  No GEMINI_API_KEY found. Using fallback prompts.");
    return generateFallbackPrompts(count);
  }

  console.log("\n  Requesting prompts from Gemini AI...");
  const geminiPrompts = await generatePromptsWithGemini(trends, GEMINI_API_KEY, count);

  if (geminiPrompts && geminiPrompts.length > 0) {
    console.log(`  Gemini generated ${geminiPrompts.length} unique prompts`);
    return geminiPrompts;
  }

  console.log("  Gemini failed. Using fallback prompts.");
  return generateFallbackPrompts(count);
}

async function runDailyGeneration() {
  console.log("========================================");
  console.log("  Stable Audio Daily Track Generator");
  console.log(`  Date: ${getTodayString()}`);
  console.log(`  Daily Quota: ${DAILY_QUOTA} tracks`);
  console.log("  Prompt Engine: Gemini AI");
  console.log("========================================");
  console.log("\n  COPYRIGHT COMPLIANCE:");
  console.log("  - All prompts generated by Gemini AI (original content)");
  console.log("  - Zedge trends used only for genre/mood inspiration");
  console.log("  - No copyrighted material used");
  console.log("  - Duplicate prompts automatically filtered\n");

  ensureOutputDir();
  cleanupOldPrompts();
  const progress = loadProgress();

  if (progress.completed >= DAILY_QUOTA) {
    console.log(`Daily quota already reached (${progress.completed}/${DAILY_QUOTA}).`);
    console.log("No tracks to generate today.");
    return progress;
  }

  console.log(`Previous progress: ${progress.completed} completed, ${progress.failed} failed`);
  const remaining = DAILY_QUOTA - progress.completed;
  console.log(`Remaining: ${remaining} tracks\n`);

  let apiKey = await getApiKey();
  if (!apiKey) {
    console.error("No Stable Audio API key available. Cannot generate.");
    return progress;
  }

  let apiClient = new StableAudioAPI(apiKey);

  let trends;
  try {
    trends = await collectTrends(30);
  } catch (err) {
    console.warn(`Failed to collect trends: ${err.message}`);
    trends = [];
  }

  let prompts = await getPromptsFromGemini(remaining + 15, trends);

  const usedPrompts = loadUsedPrompts();
  const progressPrompts = progress.tracks.map((t) => t.prompt);
  const allUsed = [...usedPrompts, ...progressPrompts];

  const uniquePrompts = prompts.filter((p) => !isDuplicate(p.prompt, allUsed));
  console.log(`\n  Final unique prompts ready: ${uniquePrompts.length}`);

  let trackNumber = progress.completed + 1;
  let consecutiveErrors = 0;
  const maxConsecutiveErrors = 5;

  for (const prompt of uniquePrompts) {
    if (trackNumber > DAILY_QUOTA) break;
    if (consecutiveErrors >= maxConsecutiveErrors) {
      console.error(`\nToo many consecutive errors (${consecutiveErrors}). Stopping.`);
      break;
    }

    try {
      const result = await generateTrack(apiClient, prompt, trackNumber);

      if (result.success) {
        progress.completed++;
        progress.tracks.push({
          number: trackNumber,
          ...result,
          generatedAt: new Date().toISOString(),
        });
        consecutiveErrors = 0;
      } else {
        progress.failed++;
        progress.errors.push({
          number: trackNumber,
          ...result,
          failedAt: new Date().toISOString(),
        });
        consecutiveErrors++;
      }
    } catch (err) {
      if (err.message === "QUOTA_EXCEEDED") {
        console.log("\n  [Quota] Current key quota exceeded.");
        progress.errors.push({
          number: trackNumber,
          error: "QUOTA_EXCEEDED",
          prompt: prompt.prompt,
          failedAt: new Date().toISOString(),
        });
        progress.failed++;
        trackNumber++;
        const newKey = await rotateApiKey(apiKey);
        if (newKey) {
          apiKey = newKey;
          apiClient = new StableAudioAPI(apiKey);
          consecutiveErrors = 0;
          continue;
        } else {
          console.error("  [Quota] No more API keys available. Stopping.");
          break;
        }
      }
      progress.failed++;
      progress.errors.push({
        number: trackNumber,
        error: err.message,
        prompt: prompt.prompt,
        failedAt: new Date().toISOString(),
      });
      consecutiveErrors++;
    }

    trackNumber++;
    saveProgress(progress);

    const delay = 2000 + Math.random() * 3000;
    await new Promise((r) => setTimeout(r, delay));
  }

  saveProgress(progress);

  console.log("\n========================================");
  console.log("  Generation Complete!");
  console.log(`  Total Generated: ${progress.completed}/${DAILY_QUOTA}`);
  console.log(`  Failed: ${progress.failed}`);
  console.log(`  Output: ${OUTPUT_DIR}`);
  console.log("========================================\n");

  return progress;
}

function generateFallbackPrompts(count) {
  const instruments = [
    "bright synth", "warm piano", "soft guitar", "elegant harp", "crisp xylophone",
    "deep bass", "shimmering bells", "gentle flute", "modern synth pads", "clean marimba",
    "digital chimes", "ambient textures", "rhythmic percussion", "smooth saxophone", "plucked strings",
  ];
  const moods = [
    "upbeat", "calm", "energetic", "gentle", "bright", "warm", "modern", "minimal", "cheerful", "elegant",
  ];
  const types = ["ringtone", "notification sound", "message alert"];
  const prompts = [];

  const usedPrompts = loadUsedPrompts();

  for (let i = 0; i < count * 2 && prompts.length < count; i++) {
    const instrument = instruments[i % instruments.length];
    const mood = moods[Math.floor(Math.random() * moods.length)];
    const type = types[i % types.length];
    const duration = 8 + Math.floor(Math.random() * 22);

    const prompt = `An original ${mood} ${type} featuring ${instrument}, ${duration} seconds, copyright free studio quality, pure instrumental`;

    if (!isDuplicate(prompt, usedPrompts) && !isDuplicate(prompt, prompts)) {
      prompts.push({
        prompt,
        duration,
        sourceCategory: type.includes("ring") ? "ringtone" : type.includes("notif") ? "notification" : "message",
        source: "fallback",
        isOriginal: true,
      });
    }
  }
  return prompts;
}

(async () => {
  try {
    await runDailyGeneration();
  } catch (err) {
    console.error("Fatal error:", err);
    process.exit(1);
  }
})();
